#!/usr/bin/env bash
cd ../..
python3 train.py\
    --model_class pointer_generator\
    --batch_size 5\
    --hidden_units 200\
    --embedding_size 200\
    --attention_units 220\
    --encoder_depth 1\
    --decoder_depth 1\
    --encoder_max_time_steps 1000\
    --decoder_max_time_steps 20\
    --display_freq 5\
    --save_freq 2000\
    --valid_freq 400\
    --model_dir checkpoints/bytecup_pointer_generator_token\
    --model_name lcsts.ckpt\
    --source_vocabulary dataset/bytecup/token/vocabs.json\
    --target_vocabulary dataset/bytecup/token/vocabs.json\
    --source_train_data dataset/bytecup/token/contents.train.txt\
    --target_train_data dataset/bytecup/token/titles.train.txt\
    --source_valid_data dataset/bytecup/token/contents.eval.txt\
    --target_valid_data dataset/bytecup/token/titles.eval.txt\
    --encoder_vocab_size 30000\
    --decoder_vocab_size 30000\
    --cell_type gru\
    --max_epochs 100000\
    --extend_vocabs True