#!/usr/bin/env bash
cd ../..
python3 lab.py\
    --beam_width 1\
    --inference_batch_size 1\
    --model_path checkpoints/lcsts_split_pointer_generator_limit/lcsts.ckpt-690000\
    --inference_input dataset/lcsts/split/sources.test.txt\
    --inference_output dataset/lcsts/split/summaries.inference.limit.5.all.filter.txt\
    --extend_vocabs True